verison: '3.8'
services:
  polyglot-tree-traversal:
    image: polyglot-tree-traversal
  
  user_App:
    build: 
      dockerfile: Dockerfile
    container_name: polyglot-tree-traversal

    volumes:
      - .:/root/polyglot-tree-traversal-example
    command: ["metacallcli", "rootNode.py"]
